# Unified Field Axiom 1 — The Composition Axiom

**Formal Name:** Unified Field Axiom 1
**Short Name:** Composition Axiom
**Date Established:** April 14, 2026
**Author:** Wang R. (Raven)

---

## Definition Statement

> **The universe universally increases in entropy, yet there exist coupling conditions under which local entropy decrease is realized. These together are the two fundamental constitutive conditions of the universe.**

---

## I. The Two Fundamental Constituents

The universe is composed of two constituents that are hierarchically equivalent and mutually dual.

### 1. Entropy Increase

Entropy increase is the universal directionality governing the evolution of isolated systems.

**Character.** A background field: pervasive, uniform, unconditional, and covering the entire universe.

**Intensity.** Moderate and always active.

**Formal statement.** The entropy of any isolated system increases strictly and monotonically:

$$\delta S > 0$$

The case δS = 0 does not occur in the real universe. It is an idealized limit retained in classical thermodynamics only for mathematical tidiness; it is a zero-measure case and corresponds to no real physical process.

**Correspondence in known physics.** The strict form of the second law of thermodynamics.

**Note on the hierarchy of thermodynamic laws.** The zeroth, first, and third laws of thermodynamics are not at the same level as the second law.

- The **zeroth law** (transitivity of thermal equilibrium) is a metrological prerequisite for the concept of temperature.
- The **first law** (conservation of energy) is the application of mechanical principles to the thermal domain.
- The **third law** (unattainability of absolute zero) is a corollary of the second law in the limit of temperature approaching zero.

Only the **second law** is treated as a universal axiom at the scale of the universe within this framework. The other three are treated as lower-level statements: metrological, mechanical, and limiting respectively.

### 2. Coupling

**Coupling is not a force. It is a structural condition — the condition for the formation of a domain.**

**Character.** A conditional field: point-like, sparse, and conditional. It holds only at positions where the coupling conditions are satisfied. It allows independent systems to enter a shared domain, to form a new composite system, and to maintain the stability of that composite.

**Position within the framework.** Coupling is not treated as an interaction between pre-existing entities. It is treated as the prior condition that permits entities to exist as entities within a shared domain. Within this framework, coupling is therefore distinguished from what is called a "force" in current physics: a force, as presently formulated, presupposes the existence of the entities it acts upon; coupling does not.

An independent system's ability to exist *as a system* is already the result of the coupling condition being satisfied at a more fundamental level within its internal structure. When two independent systems further couple into a new composite system, the coupling condition is being satisfied once again, at a larger scale. Coupling, therefore, is not a one-time event but a condition that holds recursively across scales.

**Intensity and range.**

*Per unit surface of action,* the local intensity of coupling exceeds the local intensity of entropy increase. This is why structure is able to be generated and stabilized against the entropic background.

*The range of action* of coupling is vastly smaller than that of entropy increase. Coupling is realized only at points where its structural conditions are satisfied; it does not cover most of the cosmic volume.

**Correspondence in known physics.** None. No theory at this level of the framework has been developed within existing physics. Einstein's program of unified field theory, and its successors aiming at the unification of the four fundamental forces, have been directed at the common origin of those forces. The present framework treats a different question — the formal characterization of the coupling condition itself — as an independent starting point.

---

## II. The Totalized Relation Between the Two Constituents

| Dimension of Comparison | Relation                    |
| ----------------------- | --------------------------- |
| Local intensity         | Coupling > Entropy Increase |
| Range of action         | Entropy Increase ≫ Coupling |
| Global dominance        | Entropy Increase dominates  |

**Local intensity: Coupling > Entropy Increase.** At positions where coupling conditions are satisfied, the structure generated by coupling is sufficient to resist local entropy increase, allowing the new composite system to persist as an independent entity.

**Range of action: Entropy Increase ≫ Coupling.** Entropy increase, as a background field, covers the entire universe; coupling, as a conditional field, forms only at extremely sparse positions.

**Global dominance: Entropy Increase dominates.** Although coupling locally exceeds entropy increase in intensity, its coverage is too small to reverse the global dominance of entropy. **The overall trajectory of the universe remains heat death.**

This global relation is the core of the Composition Axiom: it acknowledges the independent existence of coupling as a fundamental constituent, without thereby denying the universality of the second law of thermodynamics at the scale of the universe. The two coexist within the axiom and do not conflict.

---

## III. Direct Corollaries

### Corollary 1 — The Origin of Structure

Every structured entity in the universe is a domain formed at a position where coupling conditions have been satisfied. **It is only after a domain has formed that the entities within it exhibit observable interactions.** Within the present framework, the condition for the formation of a domain, rather than the rules of interaction within it, is taken as the primary object of investigation.

### Corollary 2 — The Four Fundamental Forces Are Not Fundamental

The four fundamental forces of modern physics — gravitation, electromagnetism, the strong force, and the weak force — are not at the fundamental level.

They are treated as derivative expressions of coupling *within already-formed domains*, at different scales and under different conditions. Within this framework, the century-long program of unifying these four forces is reframed: the object of investigation shifts from "the common origin of these four forces" to **the formal characterization of the coupling condition itself**.

### Corollary 3 — The Sparsity of Structure

Structure in the universe is local and sparse. Wherever structure exists, it exists at a position where coupling locally exceeds entropy increase against the background field. **Where the coupling condition ceases to hold, the structure is reclaimed by the background and returns to disorder.**

The proportion of "structured" entities relative to the total volume of the universe is extremely small. This is not accidental; it is a direct consequence of the fact that the range of coupling is vastly smaller than the range of entropy increase.

### Corollary 4 — Light as the Entity at the Limit of Coupling

**Light is the entity that exists when coupling is configured at its limit.**

At this limit, entropy increase still acts strictly and monotonically (δS > 0 continues to hold), but light, as a structure, has no internal degrees of freedom on which entropy increase can produce further change. Consequently, in the course of its propagation light:

- **Does not decay.** No internal degrees of freedom are available for entropy increase to act on.
- **Has no rest mass.** No rest frame exists in which it would be subject to further structural change.
- **Has zero proper time.** Its internal state does not evolve along its own worldline.

**The speed of light c is not treated as an arbitrary constant within this framework.** It is identified with the characteristic speed corresponding to the limit configuration of coupling. The upper bound on the propagation speed of any structure in the universe coincides with this limit-configuration speed, and light is the entity that realizes this configuration.

Within the Composition Axiom, light is the sole candidate entity at the limit configuration of coupling.

---

## IV. Hierarchical Structure

The Composition Axiom is the axiomatic statement of the framework. Subordinate to it are two laws at the level of specific regularities:

```
Unified Field Axiom 1 · Composition Axiom          (axiom)
├── Law of Entropy Increase    (established; the strict form of the second law, δS > 0)
└── Law of Coupling            (open; expected framework: field theory)
```

**The Composition Axiom** states the two constitutive conditions on which the framework rests.

**The Law of Entropy Increase** is the established dual term. Its mathematical expression is well-defined and physics has fully developed its content.

**The Law of Coupling** is the core open research program. It is not, strictly speaking, a mechanical law, because it does not describe the motion of pre-existing entities. Its research object is **the formal characterization of the coupling condition** — under what conditions do independent systems spontaneously enter a shared domain, form a new composite system, and tend to maintain its stability?

If the Law of Coupling is developed, its most probable mathematical framework is **field theory**. Field theory is currently the only branch of modern physics that has begun to address the question of how different fields couple to one another. In present field theory, the **coupling constants** (for example the electromagnetic coupling constant α ≈ 1/137) are input into the equations after being measured experimentally; their origin remains unexplained. The research direction opened by the Composition Axiom is precisely: why do these coupling constants take the values they do? Why do they manifest in different forms at different scales? The Law of Coupling should answer these questions.

---

## V. Research Directions

The central research object of Unified Field Axiom 1 is **the coupling condition**.

The expected output is not a single closed-form expression, but a set of conditional statements holding at multiple scales, with specific forms varying by scale. The existing descriptions of the four fundamental forces in current physics are retained as phenomenological records of the coupling condition at their respective scales, and serve as the starting data for this investigation.

Specific research directions include, but are not limited to:

1. **The coupling condition at the atomic scale.** Under what conditions does the binding of an electron to an atomic nucleus spontaneously arise and remain stable? The existing account from electromagnetism and quantum mechanics is retained as a mechanical description; the question addressed here is the condition for stable binding.
2. **Scale-recursive structure of the coupling condition.** The specific forms taken by the coupling condition at the quark, atomic, molecular, and astronomical scales, and the recursive relations between these forms.
3. **Candidate entities at the limit configuration.** Apart from light, whether other candidate entities exist at the limit configuration of coupling, and what their observable signatures would be.
4. **The origin of coupling constants.** Whether the coupling constants of existing field theory can be derived from a formal characterization of the coupling condition, rather than supplied as experimental input.

---

## VI. Scope

The body of this axiom is strictly physical. It characterizes two fundamental constitutive conditions of the universe and their totalized relation; it does not extend into any derivative domain. Applications in specific cosmological models, derivations within particular field-theoretic frameworks, and further theorems entailed by the axiom are to be developed in separate documents, subordinate in level and kept in their respective directories. The body of the Composition Axiom is not to be modified by such downstream work.

---

## Version History

| Version | Date       | Change                                                       |
| ------- | ---------- | ------------------------------------------------------------ |
| 1.0     | 2026-04-14 | Composition Axiom established; this document is the initial complete formulation. |
